import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/client/navbar/navbar";
import StoreProvider from "@/lib/redux/StoreProvider";
import { Toaster } from "@/components/ui/toaster";
import { store } from "@/lib/redux/store";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={`inter.className min-h-screen`}>
          <NavBar />
          {children}
          <Toaster />
        </body>
      </html>
    </StoreProvider>
  );
}
